package at.mci.bugtracker.controller;

import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.empty;
import static org.hamcrest.Matchers.hasItem;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.cookie;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:bug_lifecycle_it;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
class BugLifecycleIntegrationTest {

    private static final String LOGIN_JSON = """
            {
              "username": "dev",
              "password": "admin123"
            }
            """;

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUpDatabase() {
        jdbc.execute("DROP TABLE IF EXISTS activities");
        jdbc.execute("DROP TABLE IF EXISTS bug_tags");
        jdbc.execute("DROP TABLE IF EXISTS bugs");
        jdbc.execute("DROP TABLE IF EXISTS tags");
        jdbc.execute("DROP TABLE IF EXISTS users");

        jdbc.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) UNIQUE NOT NULL,
                    email VARCHAR(255) UNIQUE NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(20) NOT NULL DEFAULT 'TESTER',
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE tags (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50) UNIQUE NOT NULL,
                    color VARCHAR(7),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE bugs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    description TEXT NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'NEU',
                    priority VARCHAR(20) NOT NULL DEFAULT 'MITTEL',
                    reporter_id BIGINT NOT NULL REFERENCES users(id),
                    assignee_id BIGINT REFERENCES users(id),
                    archived BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE bug_tags (
                    bug_id BIGINT NOT NULL REFERENCES bugs(id) ON DELETE CASCADE,
                    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
                    PRIMARY KEY (bug_id, tag_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE activities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bug_id BIGINT NOT NULL REFERENCES bugs(id),
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    action VARCHAR(50) NOT NULL,
                    field VARCHAR(50),
                    old_value TEXT,
                    new_value TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.update("""
                INSERT INTO users (id, username, email, password_hash, role, active)
                VALUES (1, 'dev', 'dev@bugtracker.local',
                        '$2a$10$QYMClq1uXbiTxqhLld3wQe3Nj.aqC6V/cYwn9GR4UhLMY/kiq2wPy',
                        'DEVELOPER', TRUE)
                """);
        jdbc.update("""
                INSERT INTO tags (id, name, color) VALUES
                    (1, 'Backend', '#3B82F6'),
                    (2, 'Frontend', '#10B981'),
                    (3, 'Bug', '#EF4444')
                """);
    }

    @Test
    void fullBugLifecycle_createEditChangeStatusAndArchive() throws Exception {
        Cookie session = loginAsDeveloper();

        long bugId = createBug(session);

        editBug(session, bugId);
        changeStatus(session, bugId);
        archiveBug(session, bugId);

        assertArchivedBugIsHiddenByDefault(session, bugId);
        assertArchivedBugIsReturnedWhenIncluded(session, bugId);
    }

    private Cookie loginAsDeveloper() throws Exception {
        MvcResult result = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(LOGIN_JSON))
                .andExpect(status().isOk())
                .andExpect(cookie().exists("session"))
                .andExpect(jsonPath("$.username").value("dev"))
                .andExpect(jsonPath("$.role").value("DEVELOPER"))
                .andReturn();

        Cookie session = result.getResponse().getCookie("session");
        assertThat(session).isNotNull();
        return session;
    }

    private long createBug(Cookie session) throws Exception {
        MvcResult result = mockMvc.perform(post("/api/bugs")
                        .cookie(session)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Lifecycle integration bug",
                                  "description": "Created through the T067 lifecycle test.",
                                  "priority": "HOCH",
                                  "tagIds": [1, 2]
                                }
                                """))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.title").value("Lifecycle integration bug"))
                .andExpect(jsonPath("$.description").value("Created through the T067 lifecycle test."))
                .andExpect(jsonPath("$.status").value("NEU"))
                .andExpect(jsonPath("$.priority").value("HOCH"))
                .andExpect(jsonPath("$.archived").value(false))
                .andExpect(jsonPath("$.reporterName").value("dev"))
                .andExpect(jsonPath("$.tagIds").isArray())
                .andExpect(jsonPath("$.tagIds", hasItem(1)))
                .andExpect(jsonPath("$.tagIds", hasItem(2)))
                .andReturn();

        return ((Number) com.jayway.jsonpath.JsonPath.read(result.getResponse().getContentAsString(), "$.id"))
                .longValue();
    }

    private void editBug(Cookie session, long bugId) throws Exception {
        mockMvc.perform(put("/api/bugs/{id}", bugId)
                        .cookie(session)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Lifecycle integration bug edited",
                                  "description": "Edited through the T067 lifecycle test.",
                                  "tagIds": [3]
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(bugId))
                .andExpect(jsonPath("$.title").value("Lifecycle integration bug edited"))
                .andExpect(jsonPath("$.description").value("Edited through the T067 lifecycle test."))
                .andExpect(jsonPath("$.status").value("NEU"))
                .andExpect(jsonPath("$.tagIds").isArray())
                .andExpect(jsonPath("$.tagIds", hasItem(3)));
    }

    private void changeStatus(Cookie session, long bugId) throws Exception {
        mockMvc.perform(patch("/api/bugs/{id}/status", bugId)
                        .cookie(session)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "status": "IN_BEARBEITUNG"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(bugId))
                .andExpect(jsonPath("$.status").value("IN_BEARBEITUNG"))
                .andExpect(jsonPath("$.archived").value(false));
    }

    private void archiveBug(Cookie session, long bugId) throws Exception {
        mockMvc.perform(patch("/api/bugs/{id}/archive", bugId)
                        .cookie(session))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(bugId))
                .andExpect(jsonPath("$.status").value("ARCHIVIERT"))
                .andExpect(jsonPath("$.archived").value(true));
    }

    private void assertArchivedBugIsHiddenByDefault(Cookie session, long bugId) throws Exception {
        mockMvc.perform(get("/api/bugs")
                        .cookie(session)
                        .param("search", "Lifecycle integration bug edited"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.bugs", empty()))
                .andExpect(jsonPath("$.total").value(0));

        mockMvc.perform(get("/api/bugs/{id}", bugId)
                        .cookie(session))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(bugId))
                .andExpect(jsonPath("$.archived").value(true));
    }

    private void assertArchivedBugIsReturnedWhenIncluded(Cookie session, long bugId) throws Exception {
        mockMvc.perform(get("/api/bugs")
                        .cookie(session)
                        .param("archived", "true")
                        .param("search", "Lifecycle integration bug edited"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.total").value(1))
                .andExpect(jsonPath("$.bugs[0].id").value(bugId))
                .andExpect(jsonPath("$.bugs[0].status").value("ARCHIVIERT"))
                .andExpect(jsonPath("$.bugs[0].archived").value(true));
    }
}
