package at.mci.bugtracker.controller;

import com.jayway.jsonpath.JsonPath;
import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.empty;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.cookie;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

// End-to-End-Rollenkontrolle mit vollem Spring-Context: nur hier greift
// @EnableMethodSecurity + @PreAuthorize (im @WebMvcTest-Slice nicht).
// Deckt die DoD von T021b (TESTER -> Tag-Mutation = 403), T038a (ADMIN-CRUD
// + Delete entkoppelt Bugs ohne sie zu löschen) und T061 (TESTER darf
// kommentieren) ab. Login läuft echt über /api/auth/login -> Session-Cookie,
// SessionAuthFilter mappt die Rolle auf ROLE_<role>.
@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:role_access_it;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
class RoleAccessIntegrationTest {

    // BCrypt-Hash von "admin123" (identisch zu V4__seed_demo_users.sql).
    private static final String PW_HASH =
            "$2a$10$QYMClq1uXbiTxqhLld3wQe3Nj.aqC6V/cYwn9GR4UhLMY/kiq2wPy";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUpDatabase() {
        jdbc.execute("DROP TABLE IF EXISTS comments");
        jdbc.execute("DROP TABLE IF EXISTS activities");
        jdbc.execute("DROP TABLE IF EXISTS bug_tags");
        jdbc.execute("DROP TABLE IF EXISTS bugs");
        jdbc.execute("DROP TABLE IF EXISTS tags");
        jdbc.execute("DROP TABLE IF EXISTS users");

        jdbc.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(50) UNIQUE NOT NULL,
                    email VARCHAR(255) UNIQUE NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(20) NOT NULL DEFAULT 'TESTER',
                    active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE tags (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(50) UNIQUE NOT NULL,
                    color VARCHAR(7),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE bugs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    description TEXT NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'NEU',
                    priority VARCHAR(20) NOT NULL DEFAULT 'MITTEL',
                    reporter_id BIGINT NOT NULL REFERENCES users(id),
                    assignee_id BIGINT REFERENCES users(id),
                    archived BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE bug_tags (
                    bug_id BIGINT NOT NULL REFERENCES bugs(id) ON DELETE CASCADE,
                    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
                    PRIMARY KEY (bug_id, tag_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE activities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bug_id BIGINT NOT NULL REFERENCES bugs(id),
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    action VARCHAR(50) NOT NULL,
                    field VARCHAR(50),
                    old_value TEXT,
                    new_value TEXT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE comments (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bug_id BIGINT NOT NULL REFERENCES bugs(id) ON DELETE CASCADE,
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    content TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.update("""
                INSERT INTO users (id, username, email, password_hash, role, active) VALUES
                (1, 'admin',  'admin@bugtracker.local',  ?, 'ADMIN',     TRUE),
                (2, 'dev',    'dev@bugtracker.local',    ?, 'DEVELOPER', TRUE),
                (3, 'tester', 'tester@bugtracker.local', ?, 'TESTER',    TRUE)
                """, PW_HASH, PW_HASH, PW_HASH);
        jdbc.update("INSERT INTO tags (id, name, color) VALUES (1, 'Backend', '#3B82F6')");
        // Seed-Tag hat explizite id=1; der IDENTITY-Generator weiß davon nichts
        // und würde beim nächsten API-INSERT erneut id=1 vergeben -> PK-Kollision.
        // Generator hinter die Seed-Daten setzen.
        jdbc.execute("ALTER TABLE tags ALTER COLUMN id RESTART WITH 100");
    }

    // ---- T021b + T038a DoD: TESTER darf keine Tags anlegen ----

    @Test
    void testerCannotCreateTag_returns403() throws Exception {
        Cookie tester = login("tester");

        mockMvc.perform(post("/api/tags")
                        .cookie(tester)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"Verboten\",\"color\":\"#EF4444\"}"))
                .andExpect(status().isForbidden());

        // Auch DEVELOPER kommt an FA-16 nicht ran — nur ADMIN.
        mockMvc.perform(post("/api/tags")
                        .cookie(login("dev"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"AuchVerboten\",\"color\":\"#EF4444\"}"))
                .andExpect(status().isForbidden());
    }

    @Test
    void adminCanPerformFullTagCrud() throws Exception {
        Cookie admin = login("admin");

        MvcResult created = mockMvc.perform(post("/api/tags")
                        .cookie(admin)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"Security\",\"color\":\"#EF4444\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name").value("Security"))
                .andReturn();
        long tagId = ((Number) JsonPath.read(
                created.getResponse().getContentAsString(), "$.id")).longValue();

        mockMvc.perform(patch("/api/tags/{id}", tagId)
                        .cookie(admin)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"Security-Renamed\",\"color\":\"#000000\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Security-Renamed"));

        mockMvc.perform(delete("/api/tags/{id}", tagId).cookie(admin))
                .andExpect(status().isNoContent());

        mockMvc.perform(get("/api/tags").cookie(admin))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[?(@.name=='Security-Renamed')]", empty()));
    }

    @Test
    void duplicateTagNameReturns409() throws Exception {
        Cookie admin = login("admin");

        mockMvc.perform(post("/api/tags")
                        .cookie(admin)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"Backend\",\"color\":\"#3B82F6\"}"))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.error").value("Tag existiert bereits"));
    }

    // ---- T021b: FA-01 (TESTER darf Bugs anlegen) vs FA-04 (Edit = DEVELOPER+) ----

    @Test
    void testerCanCreateBugButCannotEditIt() throws Exception {
        Cookie tester = login("tester");

        MvcResult created = mockMvc.perform(post("/api/bugs")
                        .cookie(tester)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Tester-Bug",
                                  "description": "Vom Tester gemeldet.",
                                  "priority": "HOCH",
                                  "tagIds": [1]
                                }
                                """))
                .andExpect(status().isCreated())
                .andReturn();
        long bugId = ((Number) JsonPath.read(
                created.getResponse().getContentAsString(), "$.id")).longValue();

        // FA-04 Bearbeiten ist DEVELOPER+ -> TESTER bekommt 403.
        mockMvc.perform(put("/api/bugs/{id}", bugId)
                        .cookie(tester)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Hacked",
                                  "description": "sollte nicht durchgehen",
                                  "tagIds": []
                                }
                                """))
                .andExpect(status().isForbidden());

        // DEVELOPER darf editieren.
        mockMvc.perform(put("/api/bugs/{id}", bugId)
                        .cookie(login("dev"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Vom Dev korrigiert",
                                  "description": "ok",
                                  "tagIds": []
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.title").value("Vom Dev korrigiert"));
    }

    // ---- T061: FA-11 Kommentare sind für TESTER erlaubt ----

    @Test
    void testerCanReadAndWriteComments() throws Exception {
        Cookie tester = login("tester");
        long bugId = createBugAsTester(tester);

        mockMvc.perform(post("/api/bugs/{id}/comments", bugId)
                        .cookie(tester)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"Kann ich bestätigen.\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.content").value("Kann ich bestätigen."))
                .andExpect(jsonPath("$.userName").value("tester"))
                .andExpect(jsonPath("$.bugId").value(bugId));

        mockMvc.perform(get("/api/bugs/{id}/comments", bugId).cookie(tester))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].content").value("Kann ich bestätigen."));
    }

    @Test
    void commentOnMissingBugReturns404() throws Exception {
        mockMvc.perform(post("/api/bugs/999999/comments")
                        .cookie(login("tester"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"content\":\"Hallo?\"}"))
                .andExpect(status().isNotFound());
    }

    // ---- T038a DoD: Tag-Delete entkoppelt Bugs, löscht sie aber nicht ----

    @Test
    void deletingTagUnlinksBugsButKeepsThem() throws Exception {
        Cookie tester = login("tester");
        Cookie admin = login("admin");
        long bugId = createBugAsTester(tester);

        mockMvc.perform(delete("/api/tags/1").cookie(admin))
                .andExpect(status().isNoContent());

        mockMvc.perform(get("/api/bugs/{id}", bugId).cookie(tester))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(bugId))
                .andExpect(jsonPath("$.tagIds", empty()));
    }

    // ---- Helpers ----

    private long createBugAsTester(Cookie tester) throws Exception {
        MvcResult created = mockMvc.perform(post("/api/bugs")
                        .cookie(tester)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "title": "Bug mit Tag",
                                  "description": "hat Tag 1",
                                  "priority": "MITTEL",
                                  "tagIds": [1]
                                }
                                """))
                .andExpect(status().isCreated())
                .andReturn();
        return ((Number) JsonPath.read(
                created.getResponse().getContentAsString(), "$.id")).longValue();
    }

    private Cookie login(String username) throws Exception {
        MvcResult result = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"" + username + "\",\"password\":\"admin123\"}"))
                .andExpect(status().isOk())
                .andExpect(cookie().exists("session"))
                .andReturn();
        Cookie session = result.getResponse().getCookie("session");
        assertThat(session).isNotNull();
        return session;
    }
}
