import type { Bug, Tag, User } from '../types/bug'

export const MOCK_USERS: User[] = [
  { id: 1, username: 'marie' },
  { id: 2, username: 'tom' },
  { id: 3, username: 'lukas' },
  { id: 4, username: 'anna' },
  { id: 5, username: 'admin' },
]

export const MOCK_TAGS: Tag[] = [
  { id: 1, name: 'Backend', color: '#3b82f6' },
  { id: 2, name: 'Frontend', color: '#a855f7' },
  { id: 3, name: 'Database', color: '#10b981' },
  { id: 4, name: 'Auth', color: '#ef4444' },
  { id: 5, name: 'UX', color: '#f59e0b' },
]

export const MOCK_BUGS: Bug[] = [
  {
    id: 1,
    title: 'Login-Button reagiert nicht',
    description: 'Beim Klick auf Login passiert nichts.',
    status: 'IN_BEARBEITUNG',
    priority: 'HOCH',
    reporterId: 1,
    reporterName: 'marie',
    assigneeId: 2,
    assigneeName: 'tom',
    tagIds: [4],
    tagNames: ['Auth'],
    archived: false,
    createdAt: '2026-05-01T10:23:00Z',
    updatedAt: '2026-05-04T15:30:00Z',
  },
  {
    id: 2,
    title: 'Bug-Liste lädt langsam bei > 500 Einträgen',
    description: 'Die Liste blockt den UI-Thread für ~2s.',
    status: 'NEU',
    priority: 'MITTEL',
    reporterId: 3,
    reporterName: 'lukas',
    assigneeId: null,
    assigneeName: null,
    tagIds: [2],
    tagNames: ['Frontend'],
    archived: false,
    createdAt: '2026-05-03T09:10:00Z',
    updatedAt: '2026-05-03T09:10:00Z',
  },
  {
    id: 3,
    title: 'Passwort-Reset-Mail kommt nicht an',
    status: 'IM_REVIEW',
    priority: 'KRITISCH',
    reporterId: 4,
    reporterName: 'anna',
    assigneeId: 2,
    assigneeName: 'tom',
    tagIds: [4],
    tagNames: ['Auth'],
    archived: false,
    createdAt: '2026-04-28T16:45:00Z',
    updatedAt: '2026-05-05T11:02:00Z',
  },
  {
    id: 4,
    title: 'CSV-Export verliert Umlaute',
    status: 'ERLEDIGT',
    priority: 'NIEDRIG',
    reporterId: 1,
    reporterName: 'marie',
    assigneeId: 3,
    assigneeName: 'lukas',
    tagIds: [1],
    tagNames: ['Backend'],
    archived: false,
    createdAt: '2026-04-20T08:00:00Z',
    updatedAt: '2026-04-25T14:20:00Z',
  },
  {
    id: 5,
    title: 'Migration V4 schlägt auf leerer DB fehl',
    status: 'ABGELEHNT',
    priority: 'MITTEL',
    reporterId: 5,
    reporterName: 'admin',
    assigneeId: null,
    assigneeName: null,
    tagIds: [3],
    tagNames: ['Database'],
    archived: false,
    createdAt: '2026-04-15T12:30:00Z',
    updatedAt: '2026-04-22T09:15:00Z',
  },
  {
    id: 6,
    title: 'Filter-Dropdown verliert Selektion bei Reload',
    status: 'NEU',
    priority: 'NIEDRIG',
    reporterId: 2,
    reporterName: 'tom',
    assigneeId: 4,
    assigneeName: 'anna',
    tagIds: [2],
    tagNames: ['Frontend'],
    archived: false,
    createdAt: '2026-05-06T13:00:00Z',
    updatedAt: '2026-05-06T13:00:00Z',
  },
  {
    id: 7,
    title: 'Detail-Modal zeigt 404 nach Löschen',
    status: 'IN_BEARBEITUNG',
    priority: 'HOCH',
    reporterId: 4,
    reporterName: 'anna',
    assigneeId: 3,
    assigneeName: 'lukas',
    tagIds: [2],
    tagNames: ['Frontend'],
    archived: false,
    createdAt: '2026-05-02T17:11:00Z',
    updatedAt: '2026-05-07T10:00:00Z',
  },
  {
    id: 8,
    title: 'API-Doc fehlt für /api/notifications',
    status: 'ARCHIVIERT',
    priority: 'NIEDRIG',
    reporterId: 5,
    reporterName: 'admin',
    assigneeId: 5,
    assigneeName: 'admin',
    tagIds: [1],
    tagNames: ['Backend'],
    archived: true,
    createdAt: '2026-03-30T11:30:00Z',
    updatedAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 9,
    title: 'Keyboard-Shortcut "C" öffnet kein Modal',
    status: 'NEU',
    priority: 'MITTEL',
    reporterId: 1,
    reporterName: 'marie',
    assigneeId: null,
    assigneeName: null,
    tagIds: [5],
    tagNames: ['UX'],
    archived: false,
    createdAt: '2026-05-07T09:30:00Z',
    updatedAt: '2026-05-07T09:30:00Z',
  },
  {
    id: 10,
    title: 'Dark-Mode-Toggle persistiert nicht',
    status: 'IN_BEARBEITUNG',
    priority: 'NIEDRIG',
    reporterId: 3,
    reporterName: 'lukas',
    assigneeId: 1,
    assigneeName: 'marie',
    tagIds: [5],
    tagNames: ['UX'],
    archived: false,
    createdAt: '2026-05-04T14:00:00Z',
    updatedAt: '2026-05-08T08:45:00Z',
  },
]
